### ISSUE TITLE
v0.1.1 - not compatible with PE schema 'http://www.perkinelmer.com/PEHH/HarmonyV6'

### ISSUE THREAD

**Issue by adamananos** [broadinstitute/pe2loaddata#32]
For index.xml files exported using Harmony V6 ('http://www.perkinelmer.com/PEHH/HarmonyV6'), the schema is different such that many of the image metadata fields are no longer nested under Images, but now under Maps>Map>Entry. 

v0.1.1 fails to extract the relevant metadata.

**Comment by rlang81** [comment]
I came across the same problem (v0.1.2). I spent some time trying to tinker with the code in the repository, but it turned out to be easier to just write a quick function / script to re-write Harmony V6 index files to be compatible, at the cost of a few MBs of disk space. Here it is in case you or anyone else is looking for a bandaid fix: https://gist.github.com/rlang81/7e0ea36cf1d5ec780b1c2b94702f0383

**Comment by carmendv** [comment]
Here with the same problem, except that my index.xml file was exported using Harmony V7 ('http://www.perkinelmer.com/PEHH/HarmonyV7') I never used the V6, I went straight from V5 to V7.

**Comment by ErinWeisbart** [comment]
@rlang81 We are currently working on upgrading pe2loaddata so that it handles different/newer versions of Index files. Thanks so much for sharing your gist. Do you mind also sharing an Index file that worked with your gist?

**Comment by rlang81** [comment]
@ErinWeisbart Sure, here is an example index file before (Pre) and after (Post) processing with the gist I shared earlier. If you examine the image entries you should see that the metadata @adamananos referenced has been copied from the Map entry to the image entry in the "Post" file, which is a bandaid fix for the problem. 

[Index_Examples.zip](https://github.com/user-attachments/files/16183663/Index_Examples.zip)

**Comment by ErinWeisbart** [comment]
Thanks @rlang81 !
@sugan89 Let's see if we can easily support this Index.xml too with the changes we're making.
